#!/bin/bash

############################################################################
#
# Copyright (c) 2012 - dsixda (dislam@rocketmail.com)
#
# Android Kitchen is 100% free.  This script file is intended for personal
# and/or educational use only.  It may not be duplicated for monetary
# benefit or any other purpose without the permission of the developer.
#
############################################################################

version=0.214


if [ ! -e menu ]
then
  echo
  echo "确保您是在本工具的安装目录运行本工具，"
  echo "否则本工具可能无法正常运行。"
  echo "当进入本工具的安装目录时，"
  echo "运行./menu命令启动本工具，不要尝试使用其他命令或方法!"
  exit 0
fi

dir_list=( original_update scripts tools )
error_found=0

for check_dir in ${dir_list[@]}
do
  if [ ! -e $check_dir ]
  then
    echo "错误: 再找到目录： '$check_dir' "
    error_found=1
  fi
done

if [ $error_found == 1 ]
then
  echo
  echo "请确保本工具安装在了正确的目录下."
  exit 0
fi


chmod 755 scripts/*
scripts/check_install_dir

if [ "$?" == "1" ]
then
  exit 0
fi

scripts/init_kitchen
scripts/check_binaries

if [ "$?" == "1" ]
then
  exit 0
fi


while :
do

  clear

  echo 
  echo "============================================================"
  echo "     ROM定制工具 $version - c;dsixda p;Untitled Xperia Team "
  echo "============================================================"
  echo 
  echo "> 主菜单"
  echo
  echo "  1 - 从ROM创建工作目录"
  echo "  2 - 添加Root权限"
  echo "  3 - 添加BusyBox"
  echo "  4 - 禁用开机铃声"
  echo "  5 - 对所有apk执行Zipalign操作，优化RAM使用"
  echo "  6 - 更改ROM的清除状态"
  echo "  7 - 修改ROM显示名称"
  echo "  8 - 显示工作目录信息"
  echo 
  echo "  0 - 高级选项"
  echo " 00 - 老版本功能(很少使用到)"
  echo " 99 - 从工作目录创建刷机包"
  echo
  echo "  u - 关于/升级/捐赠"
  echo "  x - 退出本工具"
  echo
  echo 
  echo -n "请输入您的选择: "
  read opt

  if [ "$opt" != "x" ] && [ "$opt" != "u" ] && [ "$opt" != "1" ]
  then
    scripts/check_multiple_working
  fi
  
  if [ "$?" != "1" ]
  then
    case $opt in
      1) clear; scripts/check_rom; continue;;
      2) scripts/do_root; continue;;
      3) scripts/add_busybox show_help;;
      4) scripts/disable_sounds;;
      5) scripts/do_zipalign;;
      6) scripts/change_wipe;;
      7) scripts/change_rom_name;;
      8) scripts/show_rom_info;;
      0) scripts/menu_advanced $version; continue;;
      00) scripts/menu_legacy $version; continue;;
      99) scripts/build_rom;;
      u) scripts/about $version; continue;;
      x) scripts/init_kitchen; clear; echo; echo "感谢您的使用，再会～"; echo; exit 1;;
      *) echo "该选项不可用"; continue;;
    esac
  fi

  scripts/press_enter

done

